### ISSUE TITLE
Determine What Level of Education

### ISSUE THREAD

**Issue by rkilmer3** [rkilmer3/COF2024DeLozier#2]
Done when: We've determined what grade level of education we want to target.

**Comment by EthanRH11** [comment]
I would say that we stick to a lower grade level like we talked about during our meeting. I would say between second and fourth grade. Along with that, as previously talked about in the meeting I believe that we should stick with math subjects for right now. This leaves no questions up for debate and each question within our game has an exact answer.

**Comment by brandonangell30** [comment]
I think we should use basic arithmetics in our game to measure their efficiency and speed. Therefore we should stick to around 1st to 2nd grade.

**Comment by rkilmer3** [comment]
I was thinking around the third grade level myself, but 1st or 2nd is also really close to that.
